ticketing/complaint/urls.py
from django.conf.urls import url
from . import views

app_name='complaint'


urlpatterns=[
url(r'^alltics/$',views.DetailView.as_view(),name='detail'),
url(r'^$',views.Index,name='index'),
url(r'^createtic/$',views.TicketCreate.as_view(),name='create'),
url(r'^alltics/(?P<pk>[0-9]+)/$',views.TicketUpdate.as_view(),name='update'),
url(r'^alltics/(?P<pk>[0-9]+)/del/$',views.TicketDelete.as_view(),name='del'),


]

ticketing/ticketing/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('complaint.urls'))
]

ticketing/complaint/models.py
from django.db import models
from django.core.urlresolvers import reverse


dev_type= (
    ('Phone', 'Phone'),
    ('Tablet', 'Tablet'),
    ('Laptop', 'Laptop'),
    
)

stat_type= (
    ('Open', 'Open'),
    ('Close', 'Close'),
    ('Assigned', 'Assigned'),
    
)


class Ticket(models.Model):
	firstname=models.CharField(max_length=30)
	lastname=models.CharField(max_length=30)
	device=models.CharField(max_length=30,choices=dev_type)
	status=models.CharField(max_length=30,choices=stat_type,default='Open')


	def get_absolute_url(self):
		return reverse('complaint:detail')

ticketing/complaint/views.py
from django.views import generic
from django.views.generic.edit import CreateView,DeleteView, UpdateView
from django.views.generic import View
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse_lazy
from .models import Ticket


class DetailView(generic.ListView):
	template_name='complaint/detail.html'
	context_object_name='tics'

	def get_queryset(self):
		return Ticket.objects.all()


def Index(request):
	return render(request, 'complaint/index.html')


class TicketCreate(CreateView):
	model= Ticket
	fields=['firstname','lastname','device','status']

class TicketUpdate(UpdateView):
	model= Ticket
	fields=['firstname','lastname','device','status']

class TicketDelete(DeleteView):
	model=Ticket
	success_url=reverse_lazy('complaint:detail')

ticketing/complaint/templates/complaint/base.html
<head>	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	
</head>

<body background="http://wallpaper-gallery.net/images/grey-background-wallpaper/grey-background-wallpaper-5.jpg">


{% block body %}
{% endblock %}
	
</body>

ticketing/complaint/templates/complaint/detail.html
{% extends 'complaint/base.html' %}

{% block body %}

<div class="container">
  <h2>Ticket History   <a href="{% url 'complaint:index'  %}" class="btn btn-info" role="button">Home</a></h2>
            
  <table class="table table-striped">
    <thead>
      <tr>
          <th>First Name</th> 
          <th>Last Name</th>
          <th>Device</th>
          <th>Status</th>
      </tr>

              {% for tic in tics %}
          <tr>
            <td>{{tic.firstname}}</td>
            <td>{{tic.lastname}}</td>
            <td>{{tic.device}}</td>
            <td>{{tic.status}} <a href="{% url 'complaint:update' tic.id %}" class="btn btn-primary btn-sm" role="button">Edit</a>
            <form action="{% url 'complaint:del' tic.id %}" method="post" style="display: inline;">
                                  {% csrf_token %}
                                  <input type="hidden" name="tic_id" value="{{ tic.id }}" />
                                  <button type="submit" class="btn btn-default btn-sm">
                                      <span class="glyphicon glyphicon-trash"></span>
                                  </button>
                              </form>

            </td>
          </tr>
          {% endfor %}
    </thead>
    <tbody>
     
    </tbody>
  </table>
</div>

{% endblock %}

ticketing/complaint/templates/complaint/form-template.html
{% block aform%}
{% for field in form %}

	<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<span class="text-danger small"> {{ field.errors }} </span>
	</div>
	<label class="control-label col-sm-2">{{ field.label_tag }}</label>
	<div class="col-sm-10">{{ field }}</div>
		
	</label>
		
	</div>


{%endfor%}
{%endblock%}

ticketing/complaint/templates/complaint/index.html
{% extends 'complaint/base.html' %}

{% block body %}


<!-- <a href="{% url 'complaint:detail' %}" class="btn btn-info" role="button">Ticket List</a>
<a href="{% url 'complaint:create' %}" class="btn btn-info" role="button">Create Ticket</a> -->

<div class="container">
  <div class="jumbotron">
    <h1 class="text-center">Support Portal</h1>      
    <p class="text-center">Use this portal to create the tickets and to check the tickets history.</p>
  </div>

  </br>
  </br>
  </br>
  </br>

  <div class="row">
  	 <div class="col-sm-6"><a href="{% url 'complaint:detail' %}" class="btn btn-info btn-lg center-block" role="button">Ticket List</a></div>
     <div class="col-sm-6"><a href="{% url 'complaint:create' %}" class="btn btn-info btn-lg center-block" role="button">Create Ticket</a></div>

 	 
</div>





{% endblock %}

ticketing/complaint/templates/complaint/ticket_form.html
{% extends 'complaint/base.html' %}

{% block body %}

<div class="container-fluid ">

    <div class="row ">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
	                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	                {% csrf_token %}
	                {% include 'complaint/form-template.html' %}
	                <div class="form_group">
	                	<div class="col-sm-offset-2 col-sm-10">
	                		<button type="submit" class=btn btn-success>Submit</button>
	                	</div>
	                </div>
	                </form>
                 </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}